version: '2'
services:
  empresa-app:
    image: empresa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://empresa-mysql:3306/empresa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://empresa-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://empresa-elasticsearch:9200
    ports:
      - 8080:8080
  empresa-mysql:
    extends:
      file: mysql.yml
      service: empresa-mysql
  empresa-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: empresa-elasticsearch
